#!/usr/bin/env bash
# Interactive setup wizard. Writes .env.local from prompts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

if [ -f "$ENV_FILE" ]; then
  read -p ".env.local exists. Overwrite? [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
fi

ask() {
  local prompt="$1" default="${2-}" var
  if [ -n "$default" ]; then
    read -p "$prompt [$default]: " var
    echo "${var:-$default}"
  else
    read -p "$prompt: " var
    echo "$var"
  fi
}

ask_secret() {
  local prompt="$1" var
  read -s -p "$prompt: " var
  echo >&2
  echo "$var"
}

echo "=== Phone Call OpenClaw setup ==="
echo

AGENT_NAME=$(ask "Agent display name" "OpenClaw")
OWNER_NAME=$(ask "Owner display name" "the user")
APP_NAME=$(ask "Public app name (browser tab title)" "Phone Call $AGENT_NAME")

echo
OPENAI_API_KEY=$(ask_secret "OPENAI_API_KEY (required for realtime calls)")
OPENAI_REALTIME_MODEL=$(ask "OpenAI realtime model" "gpt-realtime-2")
OPENAI_REALTIME_VOICE=$(ask "OpenAI realtime voice" "marin")

echo
GW_URL=$(ask "OpenClaw gateway URL" "http://127.0.0.1:18789")
GW_TOKEN=$(ask_secret "OpenClaw gateway token (leave blank if none)")

echo
FAL_KEY=$(ask_secret "FAL_KEY (optional, enables artifact generation + avatar setup)")

echo
PORT=$(ask "Local server port" "8787")

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
OPENAI_API_KEY=$OPENAI_API_KEY
OPENAI_REALTIME_MODEL=$OPENAI_REALTIME_MODEL
OPENAI_REALTIME_VOICE=$OPENAI_REALTIME_VOICE

PUBLIC_APP_NAME=$APP_NAME
OPENCLAW_AGENT_NAME=$AGENT_NAME
OPENCLAW_OWNER_NAME=$OWNER_NAME
OPENCLAW_AGENT_VOICE_PROMPT=

OPENCLAW_GATEWAY_URL=$GW_URL
OPENCLAW_GATEWAY_TOKEN=$GW_TOKEN
OPENCLAW_HOST=local
OPENCLAW_CALL_SCOPES=all

FAL_KEY=$FAL_KEY
FAL_IMAGE_MODEL=fal-ai/nano-banana-2
FAL_VIDEO_MODEL=bytedance/seedance-2.0/fast/text-to-video
FAL_VIDEO_DURATION=4
FAL_VIDEO_ASPECT_RATIO=16:9
FAL_VIDEO_RESOLUTION=720p

PORT=$PORT
EOF

chmod 600 "$ENV_FILE"
echo
echo "Wrote $ENV_FILE"
echo "Next steps:"
echo "  ./scripts/start-tunnel.sh        # if your gateway is local, expose it via cloudflared"
echo "  ./scripts/setup-avatar.sh        # generate your avatar image + idle loop"
echo "  npm run dev                      # start the call surface"
